### ISSUE TITLE
Diagnostics layout

### ISSUE THREAD

**Issue by nebcio** [copilot-app/copilot#4]
- [x] title
- [x] two parts with recycleviews inside
- [x] error/information item (icon, title)
- [x] Dummy getters to view model

![Diagnostics](https://user-images.githubusercontent.com/73241633/229289415-79f171be-0aac-4f04-85d8-e3920779ffb3.png)

**Comment by xzqvac** [comment]
![Diagnostic_panel_3](https://user-images.githubusercontent.com/72713598/233803959-b809defa-2782-4984-9723-96a3cc6369cc.png)
![Diagnostic_panel_1](https://user-images.githubusercontent.com/72713598/233803960-aeebbcd7-dc13-42f8-b691-9d7d9493e9f0.png)
![Diagnostic_panel_2](https://user-images.githubusercontent.com/72713598/233803961-ee1fd02a-210e-49ab-b029-a81448bb69ce.png)
